// ─── Image Dataset per Category ────────────────────────────────────────────
// Each category has images with answer + URL from public sources (Wikimedia/Unsplash)
const IMAGE_DATA = {
  animals: [
    { answer: "cat", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg" },
    { answer: "dog", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/YellowLabradorLooking_new.jpg/1200px-YellowLabradorLooking_new.jpg" },
    { answer: "elephant", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/1200px-African_Bush_Elephant.jpg" },
    { answer: "lion", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/1200px-Lion_waiting_in_Namibia.jpg" },
    { answer: "tiger", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Walking_tiger_female.jpg/1200px-Walking_tiger_female.jpg" },
    { answer: "panda", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/1200px-Grosser_Panda.JPG" },
    { answer: "penguin", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Emperor_Penguin_Manchot_empereur.jpg/800px-Emperor_Penguin_Manchot_empereur.jpg" },
    { answer: "rabbit", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Oryctolagus_cuniculus_Rcdo.jpg/1200px-Oryctolagus_cuniculus_Rcdo.jpg" },
    { answer: "horse", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Nokota_Horses_croance.jpg/1200px-Nokota_Horses_croance.jpg" },
    { answer: "dolphin", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/1200px-Tursiops_truncatus_01.jpg" },
    { answer: "eagle", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/24-10-06_Bald_Eagle_Haliaeetus_leucocephalus.jpg/1200px-24-10-06_Bald_Eagle_Haliaeetus_leucocephalus.jpg" },
    { answer: "owl", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Bubo_virginianus_06.jpg/1200px-Bubo_virginianus_06.jpg" },
    { answer: "fox", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Vulpes_vulpes_laying_in_snow.jpg/1200px-Vulpes_vulpes_laying_in_snow.jpg" },
    { answer: "bear", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/2010-kodiak-bear-1.jpg/1200px-2010-kodiak-bear-1.jpg" },
    { answer: "giraffe", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/800px-Giraffe_Mikumi_National_Park.jpg" },
  ],
  fruits: [
    { answer: "apple", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/800px-Red_Apple.jpg" },
    { answer: "banana", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/800px-Banana-Single.jpg" },
    { answer: "orange", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Orange-Fruit-Pieces.jpg/800px-Orange-Fruit-Pieces.jpg" },
    { answer: "strawberry", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/800px-PerfectStrawberry.jpg" },
    { answer: "grape", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_vine.jpg/800px-Table_grapes_on_vine.jpg" },
    { answer: "watermelon", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Taiwan_2009_Tainan_City_Fruit_Arrow_Watermelon_FRD_7962.jpg/1200px-Taiwan_2009_Tainan_City_Fruit_Arrow_Watermelon_FRD_7962.jpg" },
    { answer: "pineapple", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Pineapple_and_cross_section.jpg/800px-Pineapple_and_cross_section.jpg" },
    { answer: "mango", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/800px-Hapus_Mango.jpg" },
    { answer: "kiwi", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kiwi_aka.jpg/800px-Kiwi_aka.jpg" },
    { answer: "cherry", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Cherry_Stella444.jpg/800px-Cherry_Stella444.jpg" },
    { answer: "lemon", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lemon.jpg/800px-Lemon.jpg" },
    { answer: "peach", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Autumn_Red_peridge_.jpg/800px-Autumn_Red_peridge_.jpg" },
    { answer: "coconut", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Coconut_on_white_background.jpg/800px-Coconut_on_white_background.jpg" },
    { answer: "avocado", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Hass_avocado.jpg/800px-Hass_avocado.jpg" },
    { answer: "pomegranate", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/800px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg" },
  ],
  cars: [
    { answer: "tesla", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/15_-_Tesla_Model_S_facelift_-_Frontansicht.jpg/1200px-15_-_Tesla_Model_S_facelift_-_Frontansicht.jpg" },
    { answer: "bmw", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/BMW_logo_%28gray%29.svg/800px-BMW_logo_%28gray%29.svg.png" },
    { answer: "mercedes", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/800px-Mercedes-Logo.svg.png" },
    { answer: "toyota", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Toyota.svg/800px-Toyota.svg.png" },
    { answer: "honda", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Honda_logo.svg/800px-Honda_logo.svg.png" },
    { answer: "ferrari", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Ferrari-Logo.svg/800px-Ferrari-Logo.svg.png" },
    { answer: "lamborghini", image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Lamborghini_Logo.svg/800px-Lamborghini_Logo.svg.png" },
    { answer: "porsche", image: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Porsche_logo.svg/800px-Porsche_logo.svg.png" },
    { answer: "audi", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Audi_rings_2024.svg/800px-Audi_rings_2024.svg.png" },
    { answer: "ford", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Ford_Motor_Company_Logo.svg/800px-Ford_Motor_Company_Logo.svg.png" },
    { answer: "volkswagen", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Volkswagen_logo_2019.svg/800px-Volkswagen_logo_2019.svg.png" },
    { answer: "hyundai", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Hyundai_Motor_Company_logo.svg/800px-Hyundai_Motor_Company_logo.svg.png" },
    { answer: "nissan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Nissan_logo_2020.svg/800px-Nissan_logo_2020.svg.png" },
    { answer: "mazda", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Mazda_logo_with_emblem.svg/800px-Mazda_logo_with_emblem.svg.png" },
    { answer: "chevrolet", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Chevrolet_logo.svg/800px-Chevrolet_logo.svg.png" },
  ],
  phones: [
    { answer: "iphone", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/IPhone_14_Pro_vector.svg/400px-IPhone_14_Pro_vector.svg.png" },
    { answer: "samsung", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/800px-Samsung_Logo.svg.png" },
    { answer: "google pixel", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Google_Pixel_wordmark.svg/800px-Google_Pixel_wordmark.svg.png" },
    { answer: "huawei", image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Huawei_Standard_logo.svg/800px-Huawei_Standard_logo.svg.png" },
    { answer: "xiaomi", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiaomi_logo_%282021-%29.svg/800px-Xiaomi_logo_%282021-%29.svg.png" },
    { answer: "oneplus", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/OnePlus_logo.svg/800px-OnePlus_logo.svg.png" },
    { answer: "sony", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sony_logo.svg/800px-Sony_logo.svg.png" },
    { answer: "nokia", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Nokia_wordmark.svg/800px-Nokia_wordmark.svg.png" },
    { answer: "motorola", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Motorola-logo.svg/800px-Motorola-logo.svg.png" },
    { answer: "oppo", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/OPPO_LOGO_2019.svg/800px-OPPO_LOGO_2019.svg.png" },
  ],
  logos: [
    { answer: "google", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/800px-Google_2015_logo.svg.png" },
    { answer: "apple", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/488px-Apple_logo_black.svg.png" },
    { answer: "microsoft", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/800px-Microsoft_logo_%282012%29.svg.png" },
    { answer: "amazon", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/800px-Amazon_logo.svg.png" },
    { answer: "facebook", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/800px-Facebook_Logo_%282019%29.png" },
    { answer: "netflix", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/800px-Netflix_2015_logo.svg.png" },
    { answer: "spotify", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Spotify_icon.svg/800px-Spotify_icon.svg.png" },
    { answer: "twitter", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/800px-Logo_of_Twitter.svg.png" },
    { answer: "instagram", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/800px-Instagram_logo_2016.svg.png" },
    { answer: "youtube", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/800px-YouTube_full-color_icon_%282017%29.svg.png" },
    { answer: "tiktok", image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/TikTok_logo.svg/800px-TikTok_logo.svg.png" },
    { answer: "discord", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4f/Discord_Logo_sans_texte.svg/800px-Discord_Logo_sans_texte.svg.png" },
    { answer: "slack", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Slack_icon_2019.svg/800px-Slack_icon_2019.svg.png" },
    { answer: "github", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/800px-Octicons-mark-github.svg.png" },
    { answer: "adobe", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Adobe_Systems_logo_and_wordmark.svg/800px-Adobe_Systems_logo_and_wordmark.svg.png" },
  ],
  food: [
    { answer: "pizza", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg" },
    { answer: "burger", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cheeseburger.jpg/800px-Cheeseburger.jpg" },
    { answer: "sushi", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/800px-Sushi_platter.jpg" },
    { answer: "pasta", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Penne_all%27arrabbiata.jpg/800px-Penne_all%27arrabbiata.jpg" },
    { answer: "taco", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/800px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg" },
    { answer: "ice cream", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_nut_topping_and_chocolate_sauce.jpg/800px-Ice_cream_with_whipped_cream%2C_nut_topping_and_chocolate_sauce.jpg" },
    { answer: "donut", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/800px-Glazed-Donut.jpg" },
    { answer: "cake", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/800px-A_small_cup_of_coffee.JPG" },
    { answer: "ramen", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29.jpg/800px-Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29.jpg" },
    { answer: "croissant", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Croissant%2C_France.jpg/800px-Croissant%2C_France.jpg" },
    { answer: "pancake", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Blueberry_pancakes_%283%29.jpg/800px-Blueberry_pancakes_%283%29.jpg" },
    { answer: "hotdog", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_dog_with_mustard.png/800px-Hot_dog_with_mustard.png" },
    { answer: "popcorn", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Popcorn02.jpg/800px-Popcorn02.jpg" },
    { answer: "sandwich", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Grilled_ham_and_cheese_014.JPG/800px-Grilled_ham_and_cheese_014.JPG" },
    { answer: "chocolate", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Chocolate_%28blue_background%29.jpg/800px-Chocolate_%28blue_background%29.jpg" },
  ],
  tech: [
    { answer: "keyboard", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Cherry_keyboard.jpg/1200px-Cherry_keyboard.jpg" },
    { answer: "mouse", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/3-Tasten-Maus_Microsoft.jpg/800px-3-Tasten-Maus_Microsoft.jpg" },
    { answer: "headphones", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Over-ear_headphones.jpg/800px-Over-ear_headphones.jpg" },
    { answer: "laptop", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Above_Inspiron_1501.jpg/1200px-Above_Inspiron_1501.jpg" },
    { answer: "monitor", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/LG_L194WT-SF_LCD_monitor.jpg/800px-LG_L194WT-SF_LCD_monitor.jpg" },
    { answer: "webcam", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Webcam000c1.jpg/800px-Webcam000c1.jpg" },
    { answer: "usb", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/USB_flash_drive.JPG/800px-USB_flash_drive.JPG" },
    { answer: "router", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Linksys_BEFSR41_Router_20040321.jpg/800px-Linksys_BEFSR41_Router_20040321.jpg" },
    { answer: "printer", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Laser_printers_702702.jpg/800px-Laser_printers_702702.jpg" },
    { answer: "controller", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Xbox-360-S-Controller.png/800px-Xbox-360-S-Controller.png" },
  ],
  objects: [
    { answer: "clock", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Vienna_-_Pair_of_Antique_Clocks_-_0534.jpg/800px-Vienna_-_Pair_of_Antique_Clocks_-_0534.jpg" },
    { answer: "lamp", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tiffany_Lamp_at_Treasures_in_the_Walls%2C_Acre%2C_Israel.jpg/800px-Tiffany_Lamp_at_Treasures_in_the_Walls%2C_Acre%2C_Israel.jpg" },
    { answer: "chair", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Poul_Hundevad_Dining_Chair.jpg/800px-Poul_Hundevad_Dining_Chair.jpg" },
    { answer: "scissors", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Ciseaux.jpg/800px-Ciseaux.jpg" },
    { answer: "umbrella", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Umbrella_%28PSF%29.png/800px-Umbrella_%28PSF%29.png" },
    { answer: "glasses", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Glasses_800_edit.png/800px-Glasses_800_edit.png" },
    { answer: "book", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lg-collection.jpg/800px-Lg-collection.jpg" },
    { answer: "candle", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Candle_of_hope.jpg/800px-Candle_of_hope.jpg" },
    { answer: "guitar", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/GuitareClassique5.png/400px-GuitareClassique5.png" },
    { answer: "bicycle", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camponotus_flavomarginatus_ant.jpg/1200px-Camponotus_flavomarginatus_ant.jpg" },
    { answer: "key", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Misc_pridge.jpg/800px-Misc_pridge.jpg" },
    { answer: "backpack", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Rucksack_Schweizer_Armee_1960er_a.jpg/800px-Rucksack_Schweizer_Armee_1960er_a.jpg" },
  ]
};

export default IMAGE_DATA;
